### ISSUE TITLE
Add CSS Autoprefixer

### ISSUE THREAD

**Issue by joonaaas** [WorkshopCLI/workshop-cli#8]

**Comment by salexzee** [comment]
Hey @jonasqalolino! Just added autoprefixer to the workflow. [See this commit](https://github.com/WorkshopCLI/workshop-cli/commit/c3564eb755c753e35aa7c49cd4b34b1b1e6a56e3) for reference

**Comment by salexzee** [comment]
I probably should have mentioned, this is not a change for Workshop CLI, it's a change for the Workshop Advanced Gulp workflow which is located here https://github.com/WorkshopCLI/workshop-advanced-gulp. Probably my fault for linking the wrong issues tab.
