### ISSUE TITLE
Theme language

### ISSUE THREAD

**Issue by kuduz0vic** [WorkshopCLI/workshop-cli#9]
So basically inside the theme code there is a file en.default.json, and basically there is no way to make the theme have English language. I tried copying en.default.json from debut theme and pasting it into my own theme, but after I do yarn start I have to either first save the file, or it just completely erases the content. I also tried doing it from the Shopify code editor with no success. So basically I'm just looking to add basic English to my theme, so I could use the Shopify features like newsletter and similar.

**Comment by salexzee** [comment]
This sounds like a workflow issue and not a CLI issue. Could you make this issue on whichever workflow you're having trouble with? The 2 workflow repos are: [Advanced Gulp](https://github.com/WorkshopCLI/workshop-advanced-gulp/issues) or [Basic](https://github.com/WorkshopCLI/workshop-basic/issues)
